name: my-git-actions-CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change gradle permission
        run: chmod +x gradlew

      - name: Test with gradle
        env:
          APP_ENV: "hahava"
        run: ./gradlew test

      - name: PR Comment
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          message: Test Success
          repo-token: ${{ secrets.HAHAVA_GIT_TOKEN }}